### ISSUE TITLE
Default bin being empty string has unexpected behavior

### ISSUE THREAD

**Issue by jkcclemens** [jkcclemens/bins#39]
```toml
[defaults]
bin = ""
```

```
% bins -m 'kek'
[07:44:37] ERROR – error: there is no bin called ""
```

Should give a better error message or count it as being not specified.
